### ISSUE TITLE
转换sql有点问题

### ISSUE THREAD

**Issue by csmagics** [liuyug/mdict-utils#15]
mdict -x dict.mdx --exdb

输出
                     --- Elapsed time: 0.007725 seconds ---
Traceback (most recent call last):
  File "/usr/local/bin/mdict", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.10/site-packages/mdict_utils/__main__.py", line 94, in run
    reader.unpack_to_db(args.exdir, args.mdict, zip=args.exdb_zip)
  File "/usr/local/lib/python3.10/site-packages/mdict_utils/reader.py", line 299, in unpack_to_db
    mdx = MDX(source, encoding, substyle, passcode)
  File "/usr/local/lib/python3.10/site-packages/mdict_utils/base/readmdict.py", line 622, in __init__
    MDict.__init__(self, fname, encoding, passcode)
  File "/usr/local/lib/python3.10/site-packages/mdict_utils/base/readmdict.py", line 114, in __init__
    self._key_list = self._read_keys()
  File "/usr/local/lib/python3.10/site-packages/mdict_utils/base/readmdict.py", line 364, in _read_keys
    return self._read_keys_v1v2()
  File "/usr/local/lib/python3.10/site-packages/mdict_utils/base/readmdict.py", line 453, in _read_keys_v1v2
    key_list = self._decode_key_block(key_block_compressed, key_block_info_list)
  File "/usr/local/lib/python3.10/site-packages/mdict_utils/base/readmdict.py", line 258, in _decode_key_block
    key_block = self._decode_block(key_block_compressed[i:i+compressed_size], decompressed_size)
  File "/usr/local/lib/python3.10/site-packages/mdict_utils/base/readmdict.py", line 189, in _decode_block
    assert(hex(adler32) == hex(zlib.adler32(decompressed_block) & 0xffffffff))
AssertionError

**Comment by liuyug** [comment]
没有发现问题，方便共享你的词典文件吗？

```
mdict --version
mdict version 1.3.12 - written by Yugang LIU <liuyug@gmail.com>

 mdict -x WNWCD5.mdx --exdb
100%|█████████████████████████████████████████| 107656/107656 [00:01<00:00, 72950.68rec/s]
                     --- Elapsed time: 2.646126 seconds ---
```
