### ISSUE TITLE
mdict打包报错

### ISSUE THREAD

**Issue by A6669** [liuyug/mdict-utils#6]
对下面的mdx文件可以正常解包，但是打包时会出错，即便我不做任何修改。
链接: https://pan.baidu.com/s/1Dp_aRjYgOs1UYHPpk0q6KA 提取码: h9uv
出错信息如下：
```
Pack to "牛津英语搭配词典2.mdx"
 55%|██████████████████▊               | 6642/11987 [00:00<00:00, 11309.11rec/s]                     --- Elapsed time: 1.136615 seconds ---
Traceback (most recent call last):
  File "/usr/local/bin/mdict", line 10, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.7/site-packages/mdict_utils/__main__.py", line 124, in run
    encoding=args.encoding, is_mdd=is_mdd)
  File "/usr/local/lib/python3.7/site-packages/mdict_utils/writer.py", line 316, in pack
    writer.write(outfile, callback=callback)
  File "/usr/local/lib/python3.7/site-packages/mdict_utils/writer.py", line 231, in write
    self._write_record_sect(outfile, callback=callback)
  File "/usr/local/lib/python3.7/site-packages/mdict_utils/writer.py", line 209, in _write_record_sect
    b.prepare()
  File "/usr/local/lib/python3.7/site-packages/mdict_utils/writer.py", line 86, in prepare
    self._offset_table, self._compression_type, self._version)
  File "/usr/local/lib/python3.7/site-packages/mdict_utils/base/writemdict.py", line 596, in __init__
    _MdxBlock.__init__(self, offset_table, compression_type, version)
  File "/usr/local/lib/python3.7/site-packages/mdict_utils/base/writemdict.py", line 551, in __init__
    for t in offset_table)
  File "/usr/local/lib/python3.7/site-packages/mdict_utils/base/writemdict.py", line 551, in <genexpr>
    for t in offset_table)
  File "/usr/local/lib/python3.7/site-packages/mdict_utils/writer.py", line 94, in _block_entry
    return t.get_record_null()
  File "/usr/local/lib/python3.7/site-packages/mdict_utils/writer.py", line 75, in get_record_null
    self.record_pos, self.record_size, self.encoding, self.is_mdd)
  File "/usr/local/lib/python3.7/site-packages/mdict_utils/writer.py", line 56, in get_record_null
    record_null = obj.read(size - 1)
ValueError: read length must be non-negative or -1
 65%|██████████████████████▏           | 7833/11987 [00:00<00:00, 10958.37rec/s]
```
请问如何解决此问题？

**Comment by liuyug** [comment]
```
mdict -x 牛津英语搭配词典2.mdx -d mdx
100%|████████████████████████████████████████████████████████████████▉| 11986/11987 [00:01<00:00, 8329.92rec/s]
                     --- Elapsed time: 1.505068 seconds ---
```
解压缩时，发现 11986/11987 ，字典的entry 11987个，但只能解压出 11986个！
说明字典有错误

加入错误提示后，重新解压
```
Skip entry: b'point_n_1_n10\t <h>point</h> <p-blk><p>noun</p></p-blk> <n-num>10</n-num><d neh="n">thin sharp end of sth</cl><chnsep> </chnsep><chn>\xe5\xb0\x96</chn></d><sl-g-blk sl="adj"><sl-g-head>ADJECTIVE</sl-g-head><sl-g><sb-g sb="a"><cl eid="point_n_171">fine, sharp</cl><chnsep> </chnsep><chn>\xe7\xbb\x86\xe5\xb0\x96\xef\xbc\x9b\xe9\x94\x8b\xe5\x88\xa9\xe7\x9a\x84\xe5\xb0\x96</chn></cl></sb-g></sl-g></sl-g-blk>'
```
证明你的词典确实有错误。

我已经修正软件，请重新下载运行
